#
# MRzefvGenerated
# Generated by AVX512 / MRzefv
#
# The generated project is isolated from the main AVX512 source tree.
#
ARCHS = arm64
TARGET = iphone:latest:15.0
PACKAGE_IDENTIFIER = net.delvek.mrzefv.generated
PACKAGE_NAME = MRzefvGenerated
PACKAGE_VERSION = 1.0.0
PACKAGE_REVISION = 1
PACKAGE_ARCHITECTURE = iphoneos-arm
PACKAGE_SECTION = Tweaks
PACKAGE_DESCRIPTION = AVX512 generated runtime module
define Package/$(PACKAGE_IDENTIFIER)
  Package: $(PACKAGE_IDENTIFIER)
  Name: $(PACKAGE_NAME)
  Version: $(PACKAGE_VERSION)
  Architecture: $(PACKAGE_ARCHITECTURE)
  Section: $(PACKAGE_SECTION)
  Description: $(PACKAGE_DESCRIPTION)
endef
#
# Package output
#
export THEOS_PACKAGE_DIR = $(CURDIR)/dist
#
# Rootless packaging
#
export THEOS_PACKAGE_SCHEME = rootless
THEOS_PACKAGE_INSTALL_PREFIX = /var/jb
#
# Generated dylib
#
LIBRARY_NAME = MRzefvGenerated
$(LIBRARY_NAME)_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries
#
# Generated source only.
#
# Do not pull the AVX512 application's source tree into this target.
#
$(LIBRARY_NAME)_FILES = \
	Sources/MRzefvGenerated.m
#
# Frameworks
#
$(LIBRARY_NAME)_FRAMEWORKS = \
	Foundation \
	UIKit
#
# Compiler configuration
#
$(LIBRARY_NAME)_CFLAGS = \
	-fobjc-arc \
	-fblocks \
	-miphoneos-version-min=15.0 \
	-Wall \
	-Wextra \
	-Wno-deprecated-declarations \
	-Wno-nullability-completeness
$(LIBRARY_NAME)_OBJCFLAGS = \
	-fobjc-arc
#
# Linker configuration
#
$(LIBRARY_NAME)_LDFLAGS = \
	-Wl,-no_warn_inits \
	-Wl,-search_paths_first \
	-Wl,-headerpad_max_install_names
#
# Optional generated resources
#
ifneq ($(wildcard Resources),)
$(LIBRARY_NAME)_RESOURCE_DIRS = Resources
endif
#
# Build
#
include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
#
# Additional generated targets
#
.PHONY: generated-info
generated-info:
	@echo "========================================"
	@echo " MRzefv Generated Dylib"
	@echo "========================================"
	@echo "Target:       $(LIBRARY_NAME)"
	@echo "Identifier:   $(PACKAGE_IDENTIFIER)"
	@echo "Architecture: $(ARCHS)"
	@echo "iOS minimum:  $(TARGET)"
	@echo "Package dir:  $(THEOS_PACKAGE_DIR)"
	@echo "========================================"
