//
//  MRzefvGenerated.h
//  Generated by AVX512 / MRzefv
//
//  This file belongs only to the generated build session.
//  Do not place project-specific AVX512 implementation here.
//
#ifndef MRzefvGenerated_h
#define MRzefvGenerated_h
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
NS_ASSUME_NONNULL_BEGIN
/// Unique identifier for this generated build session.
FOUNDATION_EXPORT NSString * const MRzefvGeneratedSessionID;
/// Generator name/version.
FOUNDATION_EXPORT NSString * const MRzefvGeneratedGenerator;
/// Generated target name.
FOUNDATION_EXPORT NSString * const MRzefvGeneratedTarget;
/// Initializes the generated runtime.
///
/// The implementation is generated from the user's captured
/// ViewOperation set.
FOUNDATION_EXPORT void MRzefvGeneratedInitialize(void);
/// Returns the generated build/session identifier.
FOUNDATION_EXPORT NSString *MRzefvGeneratedBuildID(void);
NS_ASSUME_NONNULL_END
#endif /* MRzefvGenerated_h */
